module.exports = [
  "Anal",
  "Brinquedos",
  "Masturbação",
  "Punição",
  "Comédia",
  "Harém",
  "Peitões",
  "Sexo Público",
  "Vida Escolar",
  "Lolicon",
  "Incesto",
  "Yuri",
  "Romance",
  "Boquete",
  "Estupro",
  "Paizuri",
  "Pettanko",
  "Jogos Eróticos",
  "Maid",
  "Eroge",
  "Ação",
  "Shotacon",
  "Virgem",
  "Ficção Científica",
  "Tentáculos",
  "Netorare",
  "Hentai",
  "Drama",
  "Kemonomimi",
  "Vanilla",
  "Nakadashi",
  "Ahegao",
  "Demônio",
  "Mind Control Monstros",
  "Oral",
  "Dupla Penetração",
  "Gang Bang",
  "Bunda Grande",
  "Creampie",
  "Pelos Pubianos",
  "Ecchi",
  "Seinen",
  "Josei",
  "Futanari",
  "Sobrenatural",
  "Dark Skin",
  "Fantasia",
  "Milf",
  "Chikan",
  "Enfermeira",
  "Professora",
  "Ashikoki",
  "Grupo",
  "Bukkake",
  "Magia",
  "Cosplay",
  "Mecha",
  "Lactação",
  "Raio-X",
  "Professor(a)",
  "Escolar",
  "Monstros",
  "Brinquedos Sexuais",
  "Gozando Dentro",
  "Óculos",
  "Peitos Grandes",
  "Sexo Anal",
  "Golden Shower",
  "Yaoi",
  "Femdom",
  "Menage",
  "Facial",
  "Policial",
  "Super Poder",
  "Terror",
  "Gerakuro",
  "Submissão",
  "Professor",
  "Demônios",
  "Horror",
  "Sci-Fi",
  "Paródia",
  "Moe",
  "Grávida",
  "Kemono",
  "Aventura",
  "Mind Break",
  "Mistério",
  "Empregada",
  "Gyaru",
  "Bara",
  "Vampiros",
  "Super Poderes",
  "Mind Control",
  "Orgia",
  "Tetas",
  "Voyeur",
  "BDSM",
  "Swimsuit",
  "Esporte",
  "Histórico",
  "Psicológico",
  "Gender Bender",
  "Slice Of Life",
  "Garotas De Escritório",
  "Shounen Ai",
  "Thriller",
  "Succubus",
  "Traição",
  "Boys Love",
  "Erótico",
  "Shounen",
  "Artes Marciais",
  "Peitoes",
  "Peitões Virgem.",
  "Preservativo",
  "Sexo Oral",
  "Ninjas",
  "Ronin",
  "Shoujo Ai",
  "Gore",
  "Gokkun",
  "Succubos",
  "Zoofilia",
  "Trem",
  "Metrô",
];
